GET http://localhost:3001/api/blogs
###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "The random title",
  "author": "John Wick",
  "url": "www.random.com",
  "userId": "6813936a4047b29f7e649df8",
  "likes": 0
}
###
DELETE http://localhost:3001/api/blogs/68121393f1f403fa1fe647ab
###
PUT http://localhost:3001/api/blogs/68124336870121dcd6449beb
Content-Type: application/json

{
  "author": "but",
  "title": "putblog",
  "url": "www.put.fi",
  "likes": 1
}
###
