### Index Persons
GET http://localhost:3001/api/persons
### Show Person
GET http://localhost:3001/api/persons/681094174dfb718196e6cd37
### Destroy person
DELETE http://localhost:3001/api/persons/6810d38ab13d5bfe6a5ec112
###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Testi Henkilö",
  "number": "123123123"
}
###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Anton"
}
###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "number": "123123123"
}
###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "123123123"
}
###