### Index
GET http://localhost:3001/api/notes
### Create
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "lol",
  "important": false
}
### Show
GET http://localhost:3001/api/notes/680fd18de0c1c292865d4f6c
### Edit
PUT http://localhost:3001/api/notes/680fd18de0c1c292865d4f6c
Content-Type: application/json

{
  "content": "HTML is hard",
  "important": true 
}
### destroy
DELETE http://localhost:3001/api/notes/6810bb310feaee3fd53728b0
