### Index
GET http://localhost:3001/api/notes
### Create
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY4MTI2Mzc2MjgxMjE3ZjViOGQ1ZWMwNyIsImlhdCI6MTc0NjAzNzkyMH0.a6ap_EotscgHj4vHWvHhFhD2ffKzGlKWmrxz1TS64yY

{
  "content": "Take magnesium",
  "important": false,
  "userId": "68126376281217f5b8d5ec07"
}
### Show
GET http://localhost:3001/api/notes/680fd18de0c1c292865d4f6c
### Edit
PUT http://localhost:3001/api/notes/680fd18de0c1c292865d4f6c
Content-Type: application/json

{
  "content": "HTML is hard",
  "important": true 
}
### destroy
DELETE http://localhost:3001/api/notes/6810bb310feaee3fd53728b0
